#!/usr/bin/env python3
"""
Consolidated dashboard — data loader.

Reads every CSV in ./Data (the exact same extracts the .twbx is built from)
and emits consolidated_data.js as `window.CD`.

Because the HTML dashboard and the Tableau workbook read the same files, the
two renderings cannot drift apart: rebuild the CSVs and both update.

Run:  python3 build_consolidated.py
"""

import csv, glob, json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "Data")

NUMERIC = re.compile(r"^-?\d+(\.\d+)?$")

def coerce(v):
    """Turn numeric-looking strings into numbers; leave everything else alone."""
    if v is None:
        return None
    s = v.strip()
    if s == "":
        return None
    if NUMERIC.match(s):
        f = float(s)
        return int(f) if f == int(f) and abs(f) < 1e15 and "." not in s else f
    return s

CD = {}
for path in sorted(glob.glob(os.path.join(DATA, "*.csv"))):
    key = os.path.basename(path)[:-4]
    with open(path, encoding="utf-8") as f:
        rows = [{k: coerce(v) for k, v in r.items()} for r in csv.DictReader(f)]
    CD[key] = rows

out = os.path.join(HERE, "consolidated_data.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("/* Generated by build_consolidated.py from ./Data — do not edit by hand. */\n")
    f.write("window.CD = ")
    json.dump(CD, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")

print("Wrote %s  (%.0f KB)" % (out, os.path.getsize(out) / 1024))
print("  tables : %d" % len(CD))
print("  rows   : %d" % sum(len(v) for v in CD.values()))
for k in sorted(CD):
    print("    %-38s %4d rows" % (k, len(CD[k])))
