#!/usr/bin/env python3
"""Bundle the aligned CSVs (plus the shared analytics extracts) into aligned_data.js."""
import csv, glob, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
NUM = re.compile(r"^-?\d+(\.\d+)?$")
def co(v):
    if v is None: return None
    s = v.strip()
    if s == "": return None
    if NUM.match(s):
        f = float(s); return int(f) if f == int(f) and "." not in s else f
    return s
AD = {}
for folder, tag in [(os.path.join(HERE, "Data"), ""),
                    (os.path.join(ROOT, "SUBMIT_TABLEAU", "Data"), "")]:
    for p in sorted(glob.glob(os.path.join(folder, "*.csv"))):
        key = os.path.basename(p)[:-4]
        if key in AD: continue          # SUBMIT_ALIGNED wins on name collision
        with open(p, encoding="utf-8") as f:
            AD[key] = [{k: co(v) for k, v in r.items()} for r in csv.DictReader(f)]
out = os.path.join(HERE, "aligned_data.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("/* Generated by build_aligned_data.py — do not edit by hand. */\nwindow.AD = ")
    json.dump(AD, f, ensure_ascii=False, separators=(",", ":"))
    f.write(";\n")
print(f"wrote aligned_data.js ({os.path.getsize(out)/1024:.0f} KB) — {len(AD)} tables, "
      f"{sum(len(v) for v in AD.values())} rows")
