#!/usr/bin/env python3
"""Bundle ./Data into case_data.js for the dashboard."""
import csv, glob, json, os, re
HERE = os.path.dirname(os.path.abspath(__file__))
NUM = re.compile(r"^-?\d+(\.\d+)?$")
def co(v):
    if v is None: return None
    s = v.strip()
    if s == "": return None
    if NUM.match(s):
        f = float(s); return int(f) if f == int(f) and "." not in s else f
    return s
D = {}
for p in sorted(glob.glob(os.path.join(HERE, "Data", "*.csv"))):
    with open(p, encoding="utf-8") as f:
        D[os.path.basename(p)[:-4]] = [{k: co(v) for k, v in r.items()} for r in csv.DictReader(f)]
out = os.path.join(HERE, "case_data.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("/* Generated by build_case_js.py — do not edit. */\nwindow.CS = ")
    json.dump(D, f, ensure_ascii=False, separators=(",", ":")); f.write(";\n")
print("case_data.js  %.0f KB  |  %d tables  |  %d rows"
      % (os.path.getsize(out)/1024, len(D), sum(len(v) for v in D.values())))
